packages:
  rust-rusty_paserk:
    # https://github.com/conradludgate/rusty-paserk
    paths: [ rust-rusty_paserk ]
    specfile_path: rust-rusty_paserk.spec
    upstream_package_name: rusty_paserk
    downstream_package_name: rust-rusty_paserk
    actions: &Actions-Package-rust2rpm
      fix-spec-file:
        - sh -c 'rust2rpm ${PACKIT_UPSTREAM_PACKAGE_NAME}'
      create-archive:
        - sh -c 'spectool -g -s0 ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
        - sh -c 'echo ${PACKIT_UPSTREAM_PACKAGE_NAME}-${PACKIT_PROJECT_VERSION}.crate'
      get-current-version:
        - sh -c 'rpmspec -q --qf "%{Version}" --srpm ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
  rust-rusty_paseto:
    # https://github.com/rrrodzilla/rusty_paseto
    paths: [ rust-rusty_paseto ]
    specfile_path: rust-rusty_paseto.spec
    upstream_package_name: rusty_paseto
    downstream_package_name: rust-rusty_paseto
    actions: *Actions-Package-rust2rpm

srpm_build_deps:
  - rust2rpm

jobs:
  - job: copr_build
    trigger: commit
    update_release: false
    targets:
      - fedora-rawhide
