# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate rusty_paserk

Name:           rust-rusty_paserk
Version:        0.3.0
Release:        %autorelease
Summary:        Platform Agnostic Serializable Keys

License:        MIT
URL:            https://crates.io/crates/rusty_paserk
Source:         %{crates_source}
# * Bump paseto dependency
Patch10:       rust-rusty_paserk-0.3.0-Bump_dependencies.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Platform Agnostic Serializable Keys (PASERK) is an extension on PASETO
for key management.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.md
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/SECURITY.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+aes-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+aes-devel %{_description}

This package contains library source intended for building other packages which
use the "aes" feature of the "%{crate}" crate.

%files       -n %{name}+aes-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+arbitrary-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+arbitrary-devel %{_description}

This package contains library source intended for building other packages which
use the "arbitrary" feature of the "%{crate}" crate.

%files       -n %{name}+arbitrary-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+argon2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+argon2-devel %{_description}

This package contains library source intended for building other packages which
use the "argon2" feature of the "%{crate}" crate.

%files       -n %{name}+argon2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+blake2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+blake2-devel %{_description}

This package contains library source intended for building other packages which
use the "blake2" feature of the "%{crate}" crate.

%files       -n %{name}+blake2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+chacha20-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+chacha20-devel %{_description}

This package contains library source intended for building other packages which
use the "chacha20" feature of the "%{crate}" crate.

%files       -n %{name}+chacha20-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ctr-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ctr-devel %{_description}

This package contains library source intended for building other packages which
use the "ctr" feature of the "%{crate}" crate.

%files       -n %{name}+ctr-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+curve25519-dalek-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+curve25519-dalek-devel %{_description}

This package contains library source intended for building other packages which
use the "curve25519-dalek" feature of the "%{crate}" crate.

%files       -n %{name}+curve25519-dalek-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ed25519-dalek-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ed25519-dalek-devel %{_description}

This package contains library source intended for building other packages which
use the "ed25519-dalek" feature of the "%{crate}" crate.

%files       -n %{name}+ed25519-dalek-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hmac-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hmac-devel %{_description}

This package contains library source intended for building other packages which
use the "hmac" feature of the "%{crate}" crate.

%files       -n %{name}+hmac-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+p384-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+p384-devel %{_description}

This package contains library source intended for building other packages which
use the "p384" feature of the "%{crate}" crate.

%files       -n %{name}+p384-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pbkdf2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pbkdf2-devel %{_description}

This package contains library source intended for building other packages which
use the "pbkdf2" feature of the "%{crate}" crate.

%files       -n %{name}+pbkdf2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sha2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sha2-devel %{_description}

This package contains library source intended for building other packages which
use the "sha2" feature of the "%{crate}" crate.

%files       -n %{name}+sha2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v3-devel %{_description}

This package contains library source intended for building other packages which
use the "v3" feature of the "%{crate}" crate.

%files       -n %{name}+v3-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v4-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v4-devel %{_description}

This package contains library source intended for building other packages which
use the "v4" feature of the "%{crate}" crate.

%files       -n %{name}+v4-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
