[[package.extra-patches]]
comments = [
    "Remove example and patch dependencies",
]
file = "rust-rusty_paseto-0.7.0-Patch_dependencies.diff"
number = 10

[scripts.prep]
post = [
    "# Remove examples",
    "rm -r examples",
]
